import { Inter } from 'next/font/google';
import './globals.css';
import ModalBienvenida from './components/ModalBienvenida';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-slate-300">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        {children}
        <ModalBienvenida />
      </body>
    </html>
  );
}
